version: '3.2'

services:

  frontend:
    image: sakovsky/priv-repo:frontend
    ports:
      - 8081:80

  backend:
    image: sakovsky/priv-repo:backend
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Mamusia123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

volumes:
  data:
    driver: local
